name = "wasm-motion-converter"
compatibility_date = "2024-01-03"

[build]
command = "pnpm install && pnpm build"

[build.upload]
dir = "dist"

[[build.upload.rules]]
type = "Text"
globs = ["**/*.html", "**/*.js", "**/*.css"]
fallthrough = false
